CREATE TABLE M_CREDITOS(
PERIODO VARCHAR(6),
TIP_REG INT,
COD_SBS_CLI DECIMAL(10),
COD_EMPRESA DECIMAL(10),
TIP_CREDITO VARCHAR(45),
COD_CUENTA VARCHAR(45),
CONDICION INT,
SALDO DECIMAL(10,2),
CLASIFICACION INT
);

CREATE TABLE M_CLIENTEDEUDA
( PERIODO VARCHAR(6),
 TIPREG INT,
 CODSBSCLI DECIMAL(10),
 FECREPORTE VARCHAR(45),
 TIPODOCTRI VARCHAR(45),
 RUC VARCHAR(45),
 TIPDOCIDE VARCHAR(45),
 NUMDOC VARCHAR(9),
 TIPPERSONA VARCHAR(45),
 TIPEMPRESA VARCHAR(45),
 CANEMPRESA INT,
 DEU_CALIF0 FLOAT,
 DEU_CALIF1 FLOAT,
 DEU_CALIF2 FLOAT,
 DEU_CALIF3 FLOAT,
 DEU_CALIF4 FLOAT,
 RAZSOC_APEC VARCHAR(45),
 APEMAT VARCHAR(45),
 APECASADA VARCHAR(45),
 NOMBRE1 VARCHAR(45),
 NOMBRE2 VARCHAR(45) 
 );

CREATE TABLE M_PERSONAS (
  NUMDOC VARCHAR2(9),
  DigVer INT,
  GrpVot VARCHAR2(50) ,
  CODUBIGEO VARCHAR2(6) ,
  ApPaterno VARCHAR2(45),
  ApMaterno VARCHAR2(45),
  Nombres VARCHAR2(45) ,
  FecNac   DATE ,
  Sexo SMALLINT
);

CREATE TABLE M_ENTIDADFINANCIERA(
  CODENTIDAD CHAR(5) ,
  NOMBANCO VARCHAR(100) ,
  NOMCORTO VARCHAR(45) ,
  TIPOENTIDAD VARCHAR(45) ,
  TIPOCOMPETENCIA VARCHAR(45) ,
  TIPOCOMPETENCIA2 VARCHAR(45) 
  );
  
CREATE TABLE M_UBIGEO
(
CODUBIGEO VARCHAR(6),
DEPARTAMENTO VARCHAR(45),
PROVINCIA VARCHAR(45),
DISTRITO VARCHAR(50),
FLG_ZONA VARCHAR(45),
FLG_CIUDAD VARCHAR(45)
);






