-- CREAR LA DIMENSION TIPO DE CRDITO:
CREATE TABLE DIM_SUBPRODUCTO(
TIPOSUBPRODUCTO CHAR(2),
DESTIPOSUBPRODUCTO VARCHAR2(100),
TIPOPROODUCTO CHAR(2),
FECACTUALIZACIONTABLA DATE
);


INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S0',	'OTROS'	,'P0', TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S1',	'Prestamo Pequeña Empresa','P1'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S2',	'Prestamo MicroEmpresa','P2'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S3',	'HIPOTECARIO NORMAL','P3'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S4',	 'HIPOTECARIO MIVIVIENDA','P3'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S5',	'PRESTAMO EFECTIVO','P4'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S6',	'PRESTAMO VEHICULAR','P4'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S7',	'SALDO DE TARJETA DE CREDITO','P5'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S8',	'LINEA DE TARJETA DE CREDITO','P5'	, TRUNC(SYSDATE));
COMMIT;			


CREATE TABLE DIM_PRODUCTO(
TIPOPRODUCTO CHAR(2),
DESTIPOPRODUCTO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);


INSERT INTO DIM_PRODUCTO  VALUES (	'P0',	'OTROS'	,TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P1',	'Prestamo Pequeña Empresa',TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P2',	'Prestamo MicroEmpresa', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P3',	'Prestamo Hipotecario', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P4',	 'Prestamo de Consumo', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P5',	'Tarjeta de Credito', TRUNC(SYSDATE));

COMMIT

-- CREAR LA DIMENSION TIPO DE CRDITO:
CREATE TABLE DIM_TIPOCREDITO(
TIPOCREDITO CHAR(2),
DESTIPOCREDITO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);
INSERT INTO DIM_TIPOCREDITO VALUES ('01',	'CrÃ©ditos Soberanos	', TRUNC(SYSDATE));
COMMIT;

SELECT * FROM DIM_TIPOCREDITO;

truncate table DIM_TIPOCREDITO

INSERT INTO DIM_TIPOCREDITO  VALUES (	'01',	'Creditos Soberanos'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'02',	'Creditos a Entidades del sector pÃºblico'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'03',	'Creditos a Bancos multilaterales de desarrollo'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'04',	'Creditos a Empresas del sistema financiero'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'05',	 'Creditos a Empresas de valores'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'06',	'Creditos Corporativos'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'07',	'Creditos a Grandes Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'08',	'Creditos a Medianas Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'09',	'Creditos a PequeÃ±as Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'10',	'Creditos a Microempresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'11',	'Creditos de Consumo revolventes'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'12',	'Creditos de Consumo no revolventes'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'13',	'Creditos Hipotecarios para vivienda'	, TRUNC(SYSDATE));
COMMIT;			


select * from DIM_TIPOCREDITO

--VERIFICAR QUE LAS DIMENSIONES ESTEN LLENAS

TRUNCATE TABLE DIM_TIPOPERSONA
DROP TABLE DIM_TIPOPERSONA
CREATE TABLE DIM_TIPOPERSONA(
TIPOPERSONA INT,
DESTIPOPERSONA VARCHAR2(150),
FECACTUALIZACIONTABLA DATE
);

INSERT INTO DIM_TIPOPERSONA  VALUES (	1,	'Persona Natural'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOPERSONA  VALUES (	2,	'Persona Jurídica'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOPERSONA  VALUES (	3,	'Personas Mancomunadas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOPERSONA  VALUES (	4,	'Patrimonios fideicometidos y vehículos de propósito especial. (De acuerdo con la definición del reglamento de titulización).'	, TRUNC(SYSDATE));

CREATE TABLE DIM_TIPODOCUMENTO(
TIPODOCUMENTO INT,
DESTIPODOCUMENTO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);

INSERT INTO DIM_TIPODOCUMENTO  VALUES (	1,	'Libreta Electoral / DNI'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO  VALUES (	2,	'Carné de Extranjería o Carta de Identidad'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO  VALUES (	5,	'Pasaporte'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO  VALUES (	3,	'VERIFICAR'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO  VALUES (	4,	'VERIFICAR'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO  VALUES (	9,	'VERIFICAR'	, TRUNC(SYSDATE));
COMMIT;


CREATE TABLE DIM_CLASIFICACION(
TIPOCLASIFICACION INT,
DESTIPOCLASIFICACION VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);

INSERT INTO DIM_CLASIFICACION  VALUES (	0,	'Normal'	, TRUNC(SYSDATE));
INSERT INTO DIM_CLASIFICACION  VALUES (	1,	'Con problemas Potenciales (CPP)'	, TRUNC(SYSDATE));
INSERT INTO DIM_CLASIFICACION  VALUES (	2,	'Deficiente'	, TRUNC(SYSDATE));
INSERT INTO DIM_CLASIFICACION  VALUES (	3,	'Dudoso'	, TRUNC(SYSDATE));
INSERT INTO DIM_CLASIFICACION  VALUES (	4,	'Pérdida'	, TRUNC(SYSDATE));
-- CREAR LA DIMENSION TIPO DE CRDITO:
CREATE TABLE DIM_TIPOCREDITO(
TIPOCREDITO CHAR(2),
DESTIPOCREDITO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);
INSERT INTO DIM_TIPOCREDITO VALUES ('01',	'Créditos Soberanos	', TRUNC(SYSDATE));
COMMIT;

SELECT * FROM DIM_TIPOCREDITO;

INSERT INTO DIM_TIPOCREDITO  VALUES (	'01',	Créditos Soberanos	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'02',	'Créditos a Entidades del sector público'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'03',	'Créditos a Bancos multilaterales de desarrollo'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'04',	'Créditos a Empresas del sistema financiero'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'05',	 'Créditos a Empresas de valores'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'06',	'Créditos Corporativos'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'07',	'Créditos a Grandes Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'08',	'Créditos a Medianas Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'09',	'Créditos a Pequeñas Empresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'10',	'Créditos a Microempresas'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'11',	'Créditos de Consumo revolventes'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'12',	'Créditos de Consumo no revolventes'	, TRUNC(SYSDATE));
INSERT INTO DIM_TIPOCREDITO  VALUES (	'13',	'Créditos Hipotecarios para vivienda'	, TRUNC(SYSDATE));
COMMIT;			



---- ANALIZAR LA DATA CLIENTE
SELECT * FROM TMP_CLIENTESRCC;

-- TIPO EMPRESA
SELECT TIP_EMPRESA, COUNT(*) FROM TMP_CLIENTESRCC
GROUP BY TIP_EMPRESA;

-- TIPO PERSONA
SELECT TIP_PERSONA, COUNT(*) FROM TMP_CLIENTESRCC
GROUP BY TIP_PERSONA;

-- TIPO DE DOCUMENTO
SELECT TIP_DOC_IDE, COUNT(*) FROM TMP_CLIENTESRCC
GROUP BY TIP_DOC_IDE;

-- CREAR LA DIMENSION TIPO DE CRDITO:
CREATE TABLE DIM_TIPODOCUMENTO(
TIPODOCUMENTO INT,
DESTIPODOCUMENTO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);

INSERT INTO DIM_TIPODOCUMENTO VALUES ('1',	'Libreta Electoral / DNI', TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO VALUES ('2',	'Carné de Extranjería o Carta de Identidad', TRUNC(SYSDATE));
INSERT INTO DIM_TIPODOCUMENTO VALUES ('3',	'Pasaporte', TRUNC(SYSDATE));
COMMIT;

SELECT * FROM DIM_TIPODOCUMENTO;


---------------------------

--------------------------------
-- EXTRAE DATOS DE UNA CADENA
--------------------------------
SELECT  ('ESTO ES UNA CADENA') FROM DUAL
UNION
SELECT  SUBSTR('ESTO ES UNA CADENA', 6) FROM DUAL
UNION
SELECT  SUBSTR('ESTO ES UNA CADENA', 6 , 2) FROM DUAL
UNION
SELECT  SUBSTR('ESTO ES UNA CADENA', 13 , 6) FROM DUAL


--------------------------------------
SELECT
CASE WHEN BANCO = 'BANCO DE CREDITO DEL PERÚ' THEN 'BCP' 
    WHEN BANCO = 'BANCO INTERNACIONAL DEL PERÚ' THEN 'BBVA'
    ELSE 'OTROS'
END,
A.*
FROM M_ENTIDAD_FINANCIERA A

-------------------------------------------

SELECT 
COD_CUENTA,
TIP_CREDITO,
CASE WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '09' THEN 'Prestamo Pequeña Empresa'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '10' THEN 'Prestamo MicroEmpresa'     
    ELSE 'OTROS'
END SUBPRODUCTO
FROM DEUDASRCC;





SELECT 
COD_CUENTA,
TIP_CREDITO,
CASE WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '09' THEN 'Prestamo Pequeña Empresa'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '10' THEN 'Prestamo MicroEmpresa'  
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) NOT IN ('23', '24', '25') THEN 'Hipotecario Normal'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) IN ('23', '24', '25') THEN 'Hipotecario mi Vivienda'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO in ('11', '12') AND SUBSTR(COD_CUENTA, 7,2 ) = ('06') 
          AND SUBSTR(COD_CUENTA, 7,4 ) <> ('0602')  THEN 'Prestamo Efectivo'
    ELSE 'OTROS'
END SUBPRODUCTO,
count(*)
FROM DEUDASRCC


---
-- LOGICA FINAL

SELECT 
COD_CUENTA,
TIP_CREDITO,
CASE WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '09' THEN 'Prestamo Pequeña Empresa'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '10' THEN 'Prestamo MicroEmpresa'  
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) NOT IN ('23', '24', '25') THEN 'Hipotecario Normal'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) IN ('23', '24', '25') THEN 'Hipotecario mi Vivienda'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO in ('11', '12') AND SUBSTR(COD_CUENTA, 7,2 ) = ('06') 
          AND SUBSTR(COD_CUENTA, 7,4 ) <> ('0602')  THEN 'Prestamo Efectivo'
    WHEN SUBSTR(COD_CUENTA,4,1) IN ('1','3','4','5', '6') AND SUBSTR(COD_CUENTA,1,2) ='14' 
         AND TIP_CREDITO IN ('11', '12') AND SUBSTR(COD_CUENTA,7,4) IN ('0602') THEN 'PRESTAMO VEHICULAR'
     WHEN SUBSTR(COD_CUENTA,4,1) IN ('1','3','4','5', '6') AND SUBSTR(COD_CUENTA,1,2) ='14' 
        AND TIP_CREDITO IN ('11', '12') AND SUBSTR(COD_CUENTA,7,2) IN ('02') THEN 'SALDO TARJETA CREDITO'          
     WHEN SUBSTR(COD_CUENTA,1,2) ='81' AND TIP_CREDITO IN ('11', '12') 
        AND SUBSTR(COD_CUENTA,4,3) IN ('923') THEN 'SALDO TARJETA CREDITO'                  
    ELSE 'OTROS'
END SUBPRODUCTO
FROM DEUDASRCC




--- CREAMOS FACT TABLE DE DEUDAS POR CLIENTE

CREATE TABLE FACT_DEUDASCLIENTE (
CODMES NUMBER,
CODSBSCLI NUMBER,
CODENTIDADFINANCIERA CHAR(5),
CODSUBPRODUCTO CHAR(2),
TIPCREDITO CHAR(2),
CODCLASIFICACION INT,
MTODEUDA NUMBER(16,2),
FECACTUALIZACIONTABLA DATE
)



-- CREAR LA DIMENSION TIPO DE SUBPRODUCTO:
CREATE TABLE DIM_SUBPRODUCTO(
TIPOSUBPRODUCTO CHAR(2),
DESTIPOSUBPRODUCTO VARCHAR2(100),
TIPOPROODUCTO CHAR(2),
FECACTUALIZACIONTABLA DATE
);


INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S0',	'OTROS'	,'P0', TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S1',	'Prestamo Pequeña Empresa','P1'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S2',	'Prestamo MicroEmpresa','P2'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S3',	'HIPOTECARIO NORMAL','P3'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S4',	 'HIPOTECARIO MIVIVIENDA','P3'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S5',	'PRESTAMO EFECTIVO','P4'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S6',	'PRESTAMO VEHICULAR','P4'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S7',	'SALDO DE TARJETA DE CREDITO','P5'	, TRUNC(SYSDATE));
INSERT INTO DIM_SUBPRODUCTO  VALUES (	'S8',	'LINEA DE TARJETA DE CREDITO','P5'	, TRUNC(SYSDATE));
COMMIT;			

SELECT * FROM DIM_SUBPRODUCTO


-- CREAR LA DIMENSION TIPO DE SUBPRODUCTO:

CREATE TABLE DIM_PRODUCTO(
TIPOPRODUCTO CHAR(2),
DESTIPOPRODUCTO VARCHAR2(100),
FECACTUALIZACIONTABLA DATE
);


INSERT INTO DIM_PRODUCTO  VALUES (	'P0',	'OTROS'	,TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P1',	'Prestamo Pequeña Empresa',TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P2',	'Prestamo MicroEmpresa', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P3',	'Prestamo Hipotecario', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P4',	 'Prestamo de Consumo', TRUNC(SYSDATE));
INSERT INTO DIM_PRODUCTO  VALUES (	'P5',	'Tarjeta de Credito', TRUNC(SYSDATE));

COMMIT;

SELECT * FROM DIM_PRODUCTO;



------------------------
--- CARGA DE TABLA FACT TABLE DESUDAS POR CLIENTE

INSERT INTO FACT_DEUDASCLIENTE (
CODMES ,
DOCIDENTIDAD,
CODENTIDADFINANCIERA ,
CODSUBPRODUCTO ,
TIPCREDITO ,
CODCLASIFICACION,
MTODEUDA,
FECACTUALIZACIONTABLA
)
SELECT 
A.periodo as CODMES ,
B.DOC_IDENTIDAD AS DOCIDENTIDAD ,
A.COD_EMPRESA AS CODENTIDADFINANCIERA ,
CASE WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '09' THEN 'S1'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '10' THEN 'S2'  
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) NOT IN ('23', '24', '25') THEN 'S3'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO = '13' AND SUBSTR(COD_CUENTA, 7,2 ) IN ('23', '24', '25') THEN 'S4'
    WHEN SUBSTR(COD_CUENTA, 4,1 ) IN ('1','3','4','5','6') AND SUBSTR(COD_CUENTA, 1,2 ) IN ('14')
          AND TIP_CREDITO in ('11', '12') AND SUBSTR(COD_CUENTA, 7,2 ) = ('06') 
          AND SUBSTR(COD_CUENTA, 7,4 ) <> ('0602')  THEN 'S5'
    WHEN SUBSTR(COD_CUENTA,4,1) IN ('1','3','4','5', '6') AND SUBSTR(COD_CUENTA,1,2) ='14' 
         AND TIP_CREDITO IN ('11', '12') AND SUBSTR(COD_CUENTA,7,4) IN ('0602') THEN 'S6'
     WHEN SUBSTR(COD_CUENTA,4,1) IN ('1','3','4','5', '6') AND SUBSTR(COD_CUENTA,1,2) ='14' 
        AND TIP_CREDITO IN ('11', '12') AND SUBSTR(COD_CUENTA,7,2) IN ('02') THEN 'S7'          
     WHEN SUBSTR(COD_CUENTA,1,2) ='81' AND TIP_CREDITO IN ('11', '12') 
        AND SUBSTR(COD_CUENTA,4,3) IN ('923') THEN 'S8'                  
    ELSE 'S0'
END AS CODSUBPRODUCTO ,
A.TIP_CREDITO AS TIPCREDITO ,
A.CLASIFICACION AS CODCLASIFICACION,
TO_NUMBER(REPLACE(A.SALDO,'.',',')) AS MTODEUDA,
TRUNC(SYSDATE) AS FECACTUALIZACIONTABLA
FROM 
DEUDASRCC A,
TMP_CLIENTESRCC B
WHERE
A.COD_SBS_CLI = B.COD_SBS_CLI (+) AND
A.PERIODO = B.PERIODO(+);


--------------------------------
--- CREACION DE FACT DEUDAS UBIGEO

INSERT INTO FACT_DEUDAS_UBIGEO (
CODMES ,
CODUBIGEO ,
CODENTIDADFINANCIERA ,
CODPRODUCTO,
MTODEUDA ,
FECACTUALIZACIONTABLE 
)
SELECT 
F.CODMES AS CODMES ,
O.Ubigeo ,
F.CODENTIDADFINANCIERA AS CODENTIDADFINANCIERA ,
S.TIPOPROODUCTO AS CODPRODUCTO,
F.MTODEUDA AS  MTODEUDA ,
TRUNC(SYSDATE) FECACTUALIZACIONTABLE 
FROM
FACT_DEUDASCLIENTE F,
ONPE O,
--TMP_UBIGEO G
DIM_SUBPRODUCTO S --,
--DIM_PRODUCTO P
WHERE
f.docidentidad = O.NumDoc(+) AND
--O.UBIGEO = G.UBIGEO(+) AND
F.CODSUBPRODUCTO = S.TIPOSUBPRODUCTO(+) --AND
--S.TIPOPRODUCTO = P.TIPOPRODUCTO(+);



